# Generated by Django 3.2 on 2022-08-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'verbose_name': 'Кинопроизведение', 'verbose_name_plural': 'Кинопроизведения'},
        ),
    ]
