# Generated by Django 3.2 on 2022-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_personfilmwork_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='full_name'),
        ),
        migrations.AlterUniqueTogether(
            name='personfilmwork',
            unique_together=set(),
        ),
    ]
