# Generated by Django 3.2 on 2022-08-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_personfilmwork_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personfilmwork',
            unique_together={('film_work', 'person')},
        ),
    ]
